version: '3'


volumes:
  ind_web_postgres_data: {}
  ind_web_postgres_data_backups: {}

services:
  plc_siemens:
    build:
      context: .
      dockerfile: ./dockerfiles/Siemens/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app  # Adjust this to your Django project directory
    ports:
      - "6000:6000"
    expose:
      - 6000
    command: /start

  
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ind_web_production_postgres
    container_name: ind_web_postgres
    volumes:
      - ind_web_postgres_data:/var/lib/postgresql/data:Z
      - ind_web_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    



networks: 
  default:
    name: ind_web_network
    external: true
