# Generated by Django 5.0.4 on 2024-04-22 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('serial_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('log', 'Log')], max_length=20)),
                ('is_alarm', models.BooleanField(default=False)),
                ('is_fault', models.BooleanField(default=False)),
                ('is_data_tag', models.BooleanField(default=False)),
                ('trigger_tag', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagmanager.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='plc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagmanager.plc'),
        ),
    ]
