# Generated by Django 5.0.4 on 2024-04-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tagmanager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmenttag",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("INT", "int"),
                    ("BOOL", "bool"),
                    ("DINT", "dint"),
                    ("WORD", "word"),
                    ("FLOAT", "float"),
                ],
                default="INT",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
